In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
data = pd.read_csv('final_movies.csv')

In [10]:
print(data.shape)
data.head()

(664, 12)


Unnamed: 0   ImdbId                              Title  IMDB_Score  \
0           0  2836166     Punk's Dead: SLC Punk 2 (2016)         5.1   
1           1  2429278     The Ghost and The Whale (2017)         4.0   
2           2  2638144                     Ben-Hur (2016)         5.7   
3           3  1431045                    Deadpool (2016)         8.0   
4           4  3498820  Captain America: Civil War (2016)         7.9   

                     Genre                                             Poster  \
0                   Comedy  https://images-na.ssl-images-amazon.com/images...   
1   Drama|Mystery|Thriller  https://images-na.ssl-images-amazon.com/images...   
2   Action|Adventure|Drama  https://images-na.ssl-images-amazon.com/images...   
3  Action|Adventure|Comedy  https://images-na.ssl-images-amazon.com/images...   
4  Action|Adventure|Sci-Fi  https://images-na.ssl-images-amazon.com/images...   

   Year  Runtime  AvgRating  NumRating            Directors  \
0  2016       75        4.8        813            nm0580669   
1  2017      105        4.3        222  nm2791125,nm2791716   
2  2016      123        5.7      39417            nm0067457   
3  2016      108        8.0     856125            nm1783265   
4  2016      147        7.8     618559  nm0751648,nm0751577   

                                             Writers  
0                                          nm0580669  
1                                          nm2791125  
2                      nm0908753,nm0164851,nm0725983  
3                                nm1014201,nm1116660  
4  nm1321655,nm1321656,nm0800209,nm0456158,nm2092...

In [12]:
movie_features = data[['IMDB_Score','Genre','Year','Runtime','AvgRating']]

In [13]:
movie_features.head()

IMDB_Score                    Genre  Year  Runtime  AvgRating
0         5.1                   Comedy  2016       75        4.8
1         4.0   Drama|Mystery|Thriller  2017      105        4.3
2         5.7   Action|Adventure|Drama  2016      123        5.7
3         8.0  Action|Adventure|Comedy  2016      108        8.0
4         7.9  Action|Adventure|Sci-Fi  2016      147        7.8

In [15]:
genrefearutes = movie_features.Genre.str.get_dummies(sep='|')

In [22]:
movie_final = pd.concat([genrefearutes,movie_features.IMDB_Score,movie_features.Year,movie_features.Runtime,movie_features.AvgRating],axis=1)

In [23]:
movie_final

Action  Adventure  Animation  Biography  Comedy  Crime  Documentary  \
0         0          0          0          0       1      0            0   
1         0          0          0          0       0      0            0   
2         1          1          0          0       0      0            0   
3         1          1          0          0       1      0            0   
4         1          1          0          0       0      0            0   
..      ...        ...        ...        ...     ...    ...          ...   
659       0          1          1          0       1      0            0   
660       0          0          0          0       1      0            0   
661       0          0          0          0       0      0            0   
662       0          0          0          0       0      0            0   
663       0          0          0          0       0      0            0   

     Drama  Family  Fantasy  ...  Short  Sport  Talk-Show  Thriller  War  \
0        0       0        0  ...      0      0          0         0    0   
1        1       0        0  ...      0      0          0         1    0   
2        1       0        0  ...      0      0          0         0    0   
3        0       0        0  ...      0      0          0         0    0   
4        0       0        0  ...      0      0          0         0    0   
..     ...     ...      ...  ...    ...    ...        ...       ...  ...   
659      0       0        0  ...      0      0          0         0    0   
660      0       0        0  ...      0      0          0         0    0   
661      1       0        0  ...      0      0          0         0    0   
662      0       0        0  ...      0      0          0         1    0   
663      1       0        0  ...      0      0          0         0    0   

     Western  IMDB_Score  Year  Runtime  AvgRating  
0          0         5.1  2016       75        4.8  
1          0         4.0  2017      105        4.3  
2          0         5.7  2016      123        5.7  
3          0         8.0  2016      108        8.0  
4          0         7.9  2016      147        7.8  
..       ...         ...   ...      ...        ...  
659        0         6.5  2016       92        6.5  
660        0         6.6  2016       73        6.5  
661        0         7.0  2016       87        6.4  
662        0         4.1  2016       98        4.1  
663        0         3.9  2016       85        3.9  

[664 rows x 27 columns]

In [25]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()
movies_final_features = min_max_scaler.fit_transform(movie_final)

In [27]:
np.round(movies_final_features,2)

array([[0.  , 0.  , 0.  , ..., 0.  , 0.15, 0.37],
       [0.  , 0.  , 0.  , ..., 0.5 , 0.21, 0.29],
       [1.  , 1.  , 0.  , ..., 0.  , 0.25, 0.5 ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 0.18, 0.6 ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.2 , 0.26],
       [0.  , 0.  , 0.  , ..., 0.  , 0.17, 0.24]])

In [31]:
movies_final_features.shape

(664, 27)

In [28]:
from sklearn.neighbors import NearestNeighbors

In [36]:
nbrs = NearestNeighbors(n_neighbors=4, algorithm='brute').fit(movies_final_features)

In [37]:
distances, indices = nbrs.kneighbors(movies_final_features)

In [58]:
indices[4]

array([ 4, 12,  5, 15], dtype=int64)

In [63]:
data.Title[15]

'Batman v Superman: Dawn of Justice (2016)'

In [65]:
import sqlite3

In [70]:
con = sqlite3.connect("db.sqlite3", isolation_level=None,
                           detect_types=sqlite3.PARSE_COLNAMES)

In [71]:
cursor = con.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('django_migrations',), ('sqlite_sequence',), ('Movies_genre',), ('Movies_movie_Directors',), ('Movies_movie_Genres',), ('Movies_movie_Writers',), ('auth_group_permissions',), ('auth_user_groups',), ('auth_user_user_permissions',), ('django_admin_log',), ('django_content_type',), ('auth_permission',), ('auth_user',), ('auth_group',), ('django_session',), ('Movies_movie',), ('Movies_newrating',), ('authtoken_token',), ('Movies_people',)]


In [111]:
Movies = pd.read_sql_query("SELECT * FROM Movies_movie", con)

In [192]:
Movies[Movies.Title.str.contains("Batman")]

id   ImdbId                                  Title  Imdb_rating  \
15    38  2975590     Batman v Superman: Dawn of Justice          6.7   
47    70  4870838                      Batman: Bad Blood          6.8   
377  400  4853102               Batman: The Killing Joke          6.5   
521  544  5896146    Batman Unlimited: Mechs vs. Mutants          5.8   
651  674  5973626  Batman: Return of the Caped Crusaders          7.0   

                                            Image_link  Year  Num_ratings  \
15   https://images-na.ssl-images-amazon.com/images...  2016       595671   
47   https://images-na.ssl-images-amazon.com/images...  2016        18027   
377  https://images-na.ssl-images-amazon.com/images...  2016        45616   
521  https://images-na.ssl-images-amazon.com/images...  2016         1289   
651  https://images-na.ssl-images-amazon.com/images...  2016         4304   

     RunTime  Rating  
15       151     6.5  
47        72     6.8  
377       76     6.4  
521       72     5.9  
651       78     6.8

In [ ]:
Movies

In [160]:
Movie_genres = pd.read_sql_query('select * from Movies_movie_Genres',con)

In [161]:
Gneres = pd.read_sql_query('select * from Movies_genre',con)

In [162]:
Genres = Gneres.set_index('id').to_dict()

In [163]:
Movie_genres.genre_id = Movie_genres.genre_id.apply(lambda x: Genres['genre'][x])

In [164]:
Movie_genres

id  movie_id  genre_id
0       61        23    Comedy
1       62        24     Drama
2       63        24   Mystery
3       64        24  Thriller
4       65        25    Action
...    ...       ...       ...
1407  1468       682    Comedy
1408  1469       683    Comedy
1409  1470       684     Drama
1410  1471       685  Thriller
1411  1472       686     Drama

[1412 rows x 3 columns]

In [165]:
Movie_genres = Movie_genres.groupby('movie_id')['genre_id'].apply('|'.join).reset_index()

In [166]:
genre_features = Movie_genres.genre_id.str.get_dummies(sep='|')

In [167]:
Movie_genres = pd.concat([Movie_genres.drop('genre_id', axis=1), genre_features], axis=1)

In [168]:
Movie_genres

movie_id  Action  Adventure  Animation  Biography  Comedy  Crime  \
0          23       0          0          0          0       1      0   
1          24       0          0          0          0       0      0   
2          25       1          1          0          0       0      0   
3          26       1          1          0          0       1      0   
4          27       1          1          0          0       0      0   
..        ...     ...        ...        ...        ...     ...    ...   
659       682       0          1          1          0       1      0   
660       683       0          0          0          0       1      0   
661       684       0          0          0          0       0      0   
662       685       0          0          0          0       0      0   
663       686       0          0          0          0       0      0   

     Documentary  Drama  Family  ...  Musical  Mystery  Romance  Sci-Fi  \
0              0      0       0  ...        0        0        0       0   
1              0      1       0  ...        0        1        0       0   
2              0      1       0  ...        0        0        0       0   
3              0      0       0  ...        0        0        0       0   
4              0      0       0  ...        0        0        0       1   
..           ...    ...     ...  ...      ...      ...      ...     ...   
659            0      0       0  ...        0        0        0       0   
660            0      0       0  ...        0        0        0       0   
661            0      1       0  ...        0        0        0       0   
662            0      0       0  ...        0        0        0       0   
663            0      1       0  ...        0        0        0       0   

     Short  Sport  Talk-Show  Thriller  War  Western  
0        0      0          0         0    0        0  
1        0      0          0         1    0        0  
2        0      0          0         0    0        0  
3        0      0          0         0    0        0  
4        0      0          0         0    0        0  
..     ...    ...        ...       ...  ...      ...  
659      0      0          0         0    0        0  
660      0      0          0         0    0        0  
661      0      0          0         0    0        0  
662      0      0          0         1    0        0  
663      0      0          0         0    0        0  

[664 rows x 24 columns]

In [171]:
Movie_feartures = Movies[['id','Title', 'Imdb_rating', 'RunTime','Rating','Year']]

In [174]:
Movie_feartures = pd.concat([Movie_feartures.set_index('id'), Movie_genres.set_index('movie_id')], axis=1, join='inner')

In [175]:
Movie_feartures

Title  Imdb_rating  RunTime  Rating  Year  \
23         Punk's Dead: SLC Punk 2          5.1       75     4.8  2016   
24         The Ghost and The Whale          4.0      105     4.3  2017   
25                         Ben-Hur          5.7      123     5.7  2016   
26                        Deadpool          8.0      108     8.0  2016   
27      Captain America: Civil War          7.9      147     7.8  2016   
..                             ...          ...      ...     ...   ...   
682                         Trolls          6.5       92     6.5  2016   
683  Russell Peters: Almost Famous          6.6       73     6.5  2016   
684                Girl in the Box          7.0       87     6.4  2016   
685            Hidden in the Woods          4.1       98     4.1  2016   
686                             37          3.9       85     3.9  2016   

     movie_id  Action  Adventure  Animation  Biography  ...  Musical  Mystery  \
23         23       0          0          0          0  ...        0        0   
24         24       0          0          0          0  ...        0        1   
25         25       1          1          0          0  ...        0        0   
26         26       1          1          0          0  ...        0        0   
27         27       1          1          0          0  ...        0        0   
..        ...     ...        ...        ...        ...  ...      ...      ...   
682       682       0          1          1          0  ...        0        0   
683       683       0          0          0          0  ...        0        0   
684       684       0          0          0          0  ...        0        0   
685       685       0          0          0          0  ...        0        0   
686       686       0          0          0          0  ...        0        0   

     Romance  Sci-Fi  Short  Sport  Talk-Show  Thriller  War  Western  
23         0       0      0      0          0         0    0        0  
24         0       0      0      0          0         1    0        0  
25         0       0      0      0          0         0    0        0  
26         0       0      0      0          0         0    0        0  
27         0       1      0      0          0         0    0        0  
..       ...     ...    ...    ...        ...       ...  ...      ...  
682        0       0      0      0          0         0    0        0  
683        0       0      0      0          0         0    0        0  
684        0       0      0      0          0         0    0        0  
685        0       0      0      0          0         1    0        0  
686        0       0      0      0          0         0    0        0  

[664 rows x 52 columns]

In [177]:
min_max_scaler = MinMaxScaler()
movies_final_features = min_max_scaler.fit_transform(Movie_feartures.drop(['Title','movie_id'], axis=1 ))

In [179]:
movies_final_features.shape

(664, 50)

In [180]:
from sklearn.neighbors import NearestNeighbors

In [181]:
nbrs = NearestNeighbors(n_neighbors=4, algorithm='brute').fit(movies_final_features)
distances, indices = nbrs.kneighbors(movies_final_features)

In [183]:
indices[27]

array([ 27, 650, 642, 316], dtype=int64)

In [187]:
Movie_feartures.Title[316]

'La pazza gioia'